POST http://localhost:8080/v1/register/member
Content-Type: application/json

{
  "username": "Rick",
  "password": "Sanchez",
  "email": "krzysztof.mckulacz@gmail.com",
  "role": "TEACHER"
}

###

POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "email": "krzysztof.mckulacz@gmail.com",
  "password": "1234"
}

###

POST http://localhost:8080/create-team
Content-Type: application/json

{
  "subject": "MATH",
  "password": "2137"
}
