POST http://localhost:8080/v1/register/member
Content-Type: application/json

{
  "username": "bartuś",
  "password": "dupacycki",
  "email": "krzysztof.mckulacz@gmail.com",
  "role": "STUDENT"
}

###

POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "email": "krzysztof.mckulacz@gmail.com",
  "password": "1234"
}

###
