spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classconect
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
