spring:
  datasource:
    url: jdbc:postgresql:postgres://ymwoamye:P4R9VNHf4zMDzIn-c5NVJM5Cq2lfOoe7@lucky.db.elephantsql.com/ymwoamye
    username: ymwoamye
    password: P4R9VNHf4zMDzIn-c5NVJM5Cq2lfOoe7
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
mail:
  host: smtp.gmail.com
  port: 587
  username: classconect0@gmail.com
  password: cyuxgbkoztchgxke
  protocol: smtp
  auth: true
  sslTrust: smtp.gmail.com
  starttlsEnable: true
  starttlsRequired: true
  debug: true
backend:
  host: localhost
  port: 8080
