spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classconect
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true