spring:
  datasource:
    url: jdbc:h2:mem:local
    username: root
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true