spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/classconect
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
mail:
  host: smtp.gmail.com
  port: 587
  username: classconect0@gmail.com
  password: cyuxgbkoztchgxke
  protocol: smtp
  auth: true
  sslTrust: smtp.gmail.com
  starttlsEnable: true
  starttlsRequired: true
  debug: true
backend:
  host: localhost
  port: 8080
